name: Firsst Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step one
      run: echo "Log from step one"
    - name: Step two
      run: echo "Log from step two"
      
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      run: echo "Hola you finished"
      
